### ISSUE TITLE
Umami logo should be on left, not right

### ISSUE THREAD

**Issue by jrbeeman** [balsama/engage-demo#8]
In the current version of the demo, the Umami logo is in the right of the header. It should be on the left. See screenshots below.

Current Engage demo:
<img width="878" alt="engage_atx_-_innovation_showcase_2018_-_google_slides" src="https://user-images.githubusercontent.com/211558/46424893-398faa00-c6ef-11e8-95f2-f06c2d782749.png">

Correct header:
<img width="1396" alt="home___drupal" src="https://user-images.githubusercontent.com/211558/46424909-3e545e00-c6ef-11e8-9a9d-c7a7e91f8349.png">

**Comment by balsama** [comment]
This is built out to the dev environment and I've confirmed it fixes the problem:
http://engagedemof44xea2lhe.devcloud.acquia-sites.com/

Ready to merge.
